version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: dompis_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: n8n
      MYSQL_USER: n8n_user
      MYSQL_PASSWORD: n8n_password
    ports:
      - '3307:3306'
    volumes:
      - dompis_mysql_dev_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: dompis_redis_dev
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - dompis_redis_dev_data:/data

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dompis_phpmyadmin_dev
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    depends_on:
      - mysql

  n8n:
    image: n8nio/n8n:latest
    container_name: dompis_n8n_dev
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      DB_TYPE: mysqldb
      DB_MYSQLDB_HOST: mysql
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_DATABASE: n8n
      DB_MYSQLDB_USER: n8n_user
      DB_MYSQLDB_PASSWORD: n8n_password

      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      TZ: Asia/Jakarta
      N8N_ENCRYPTION_KEY: dev_key_123
      N8N_LOG_LEVEL: debug

    depends_on:
      - mysql
    volumes:
      - n8n_dev_data:/home/node/.n8n
      - ./uploads:/data/uploads

volumes:
  dompis_mysql_dev_data:
  dompis_redis_dev_data:
  n8n_dev_data:
