module.exports = {
  apps: [
    {
      name: 'dompis-server',
      script: '/www/wwwroot/dompis_v2/node_modules/.bin/next',
      args: 'start -p 9005',
      cwd: '/www/wwwroot/dompis_v2',
      instances: Number(process.env.WEB_INSTANCES || 1),
      exec_mode:
        Number(process.env.WEB_INSTANCES || 1) > 1 ? 'cluster' : 'fork',
      max_memory_restart: '8192M',
      node_args: '--max-old-space-size=4096',
      env: {
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
        PORT: '9005',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '20',
        PRISMA_POOL_TIMEOUT: '30',
         TICKETS_CACHE_TTL: '10',
        DASHBOARD_CACHE_TTL: '15',
        CACHE_MAX_BYTES: '4194304',
        DAILY_EXPORT_MAX_ROWS: '100000',
        TECH_PERFORMANCE_EXPORT_MAX_ROWS: '10000',
        LIVE_REFRESH_ENABLED: 'false',
        QOSMIC_BRIDGE_ENABLED: 'true',
        QOSMIC_BRIDGE_BASE_URL: 'https://qosmic.solusee.id/api/metabase-bridge',
        QOSMIC_BRIDGE_TOKEN: 'mbb_99d24c46d664c3d2d6f463c6ab5698eefced0328',
        QOSMIC_BRIDGE_RATE_LIMIT_PER_MIN: '20',
        QOSMIC_BRIDGE_TIMEOUT_MS: '15000',
        QOSMIC_BRIDGE_RETRY_MAX: '4',
        QOSMIC_BRIDGE_MAX_CONCURRENT: '3',
        VALIDASI_FLAG_ENABLED: 'true',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      listen_timeout: 15000,
      health_check_grace_period: 3000,
      error_file: '/var/log/dompis/web-error.log',
      out_file: '/var/log/dompis/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-ops-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1024M',
      node_args: '--max-old-space-size=768',
      env: {
        NODE_ENV: 'production',
        CRON_ENABLED: 'true',
        WORKER_STARTUP_DELAY_MS: '40000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '8',
        PRISMA_POOL_TIMEOUT: '60',
        EXTERNAL_DB_CONNECTION_LIMIT: '6',
        EXTERNAL_DB_CONNECT_TIMEOUT_MS: '10000',
        DLQ_RETRY_INTERVAL_MINUTES: '5',
        HEALTH_CHECK_INTERVAL_MINUTES: '15',
        RECONCILIATION_ENABLED: 'true',
        RECONCILIATION_CRON: '0 6 * * *',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/ops-worker-error.log',
      out_file: '/var/log/dompis/ops-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-data-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-data.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '870M',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '0',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '15',
        PRISMA_POOL_TIMEOUT: '60',
        PRISMA_SLOW_QUERY_MS: '2000',
        EXTERNAL_DB_CONNECTION_LIMIT: '6',
        EXTERNAL_DB_CONNECT_TIMEOUT_MS: '10000',
        DATA_WORKER_ENABLED: 'true',
        DATA_WORKER_INTERVAL_MINUTES: '1',
        DATA_WORKER_TIMEOUT_MINUTES: '30',
        DATA_WORKER_LOCK_TTL_SECONDS: '2100',
        DATA_WORKER_MAX_CONSECUTIVE_ERRORS: '5',
        DATA_WORKER_CIRCUIT_RESET_MINUTES: '10',
        DATA_WORKER_RUN_ON_START: 'true',
        DATA_WORKER_TRIGGER_PROJECTION: 'true',
        DATA_WORKER_BACKFILL_ENABLED: 'false',
        EXTERNAL_TABLE_NAMES: 'piloting_tickets,nossa,nossa_closed',
        INGESTION_ENABLED: 'true',
        INGESTION_TIMEOUT_MINUTES: '30',
        INGESTION_CHUNK_SIZE: '100',
        INGESTION_BATCH_SIZE: '500',
        INGESTION_WRITE_CHUNK_SIZE: '500',
        INGESTION_CONCURRENCY: '2',
        INGESTION_RETRY_MAX: '3',
        INGESTION_RETRY_BASE_MS: '250',
        INGESTION_MAX_CONSECUTIVE_ERRORS: '5',
        INGESTION_CIRCUIT_RESET_MINUTES: '10',
        INGESTION_CURSOR_STALE_HOURS: '24',
        STATUS_REFRESH_ENABLED: 'true',
        STATUS_REFRESH_INTERVAL_MINUTES: '2',
        STATUS_REFRESH_BATCH_SIZE: '15',
        STATUS_REFRESH_MIN_BATCH_SIZE: '10',
        STATUS_REFRESH_MAX_BATCH_SIZE: '30',
        STATUS_REFRESH_RECHECK_MINUTES: '2',
        STATUS_REFRESH_UPDATE_CHUNK_SIZE: '25',
        STATUS_REFRESH_SEED_BATCH_SIZE: '50',
        STATUS_REFRESH_SEED_TIMEOUT_MS: '15000',
        STATUS_REFRESH_TIMEOUT_MINUTES: '5',
        STATUS_REFRESH_FAST_RUN_THRESHOLD_MS: '10000',
        STATUS_REFRESH_SLOW_RUN_THRESHOLD_MS: '60000',
        STATUS_REFRESH_MAX_CONSECUTIVE_ERRORS: '5',
        STATUS_REFRESH_CIRCUIT_RESET_MINUTES: '10',
        STATUS_REFRESH_RUN_ON_START: 'true',
        STATUS_REFRESH_TRIGGER_PROJECTION: 'true',
        ACTIVE_REFRESH_ENABLED: 'true',
        ACTIVE_REFRESH_BATCH_SIZE: '50',
        ACTIVE_REFRESH_MIN_BATCH_SIZE: '40',
        ACTIVE_REFRESH_MAX_BATCH_SIZE: '150',
        ACTIVE_REFRESH_MAX_SCAN_PER_RUN: '500',
        ACTIVE_REFRESH_TIMEOUT_MINUTES: '5',
        ACTIVE_REFRESH_FAST_RUN_THRESHOLD_MS: '10000',
        ACTIVE_REFRESH_SLOW_RUN_THRESHOLD_MS: '60000',
        ACTIVE_REFRESH_MAX_CONSECUTIVE_ERRORS: '5',
        ACTIVE_REFRESH_CIRCUIT_RESET_MINUTES: '10',
        ACTIVE_REFRESH_RUN_ON_START: 'true',
        LIVE_REFRESH_ENABLED: 'false',
        QOSMIC_BRIDGE_ENABLED: 'true',
        QOSMIC_BRIDGE_BASE_URL: 'https://qosmic.solusee.id/api/metabase-bridge',
        QOSMIC_BRIDGE_TOKEN: 'mbb_99d24c46d664c3d2d6f463c6ab5698eefced0328',
        QOSMIC_BRIDGE_RATE_LIMIT_PER_MIN: '20',
        QOSMIC_BRIDGE_TIMEOUT_MS: '15000',
        QOSMIC_BRIDGE_RETRY_MAX: '4',
        QOSMIC_BRIDGE_MAX_CONCURRENT: '3',
        QOSMIC_BRIDGE_INGESTION_MAX_PER_MIN: '14',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/data-worker-error.log',
      out_file: '/var/log/dompis/data-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-projection-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-projection.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '870M',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '10000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '6',
        PRISMA_POOL_TIMEOUT: '60',
        PRISMA_SLOW_QUERY_MS: '2000',
        PROJECTION_ENABLED: 'true',
        PROJECTION_INTERVAL_MINUTES: '2',
        PROJECTION_TIMEOUT_MINUTES: '15',
        PROJECTION_LOCK_TTL_SECONDS: '900',
        PROJECTION_BATCH_SIZE: '250',
        PROJECTION_WRITE_CHUNK_SIZE: '50',
        PROJECTION_CONCURRENCY: '1',
        PROJECTION_RETRY_MAX: '3',
        PROJECTION_RETRY_BASE_DELAY_MS: '250',
        PROJECTION_TRANSACTION_TIMEOUT_MS: '120000',
        PROJECTION_CIRCUIT_RESET_MINUTES: '10',
        PROJECTION_FULL_SCAN_ENABLED: 'true',
        PROJECTION_FULL_SCAN_CRON: '0 3 * * *',
        PROJECTION_RUN_ON_START: 'true',
        PROJECTION_RECONCILIATION_INTERVAL: '50',
        TICKETS_CACHE_TTL: '15',
        DASHBOARD_CACHE_TTL: '30',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/projection-worker-error.log',
      out_file: '/var/log/dompis/projection-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
  ],
};
