module.exports = {
  apps: [
    {
      name: 'dompis-server',
      script: '/www/wwwroot/dompis_v2/node_modules/.bin/next',
      args: 'start -p 9005',
      cwd: '/www/wwwroot/dompis_v2',
      instances: Number(process.env.WEB_INSTANCES || 1),
      exec_mode:
        Number(process.env.WEB_INSTANCES || 1) > 1 ? 'cluster' : 'fork',
      max_memory_restart: '16000M',
      node_args: '--max-old-space-size=4096',
      env: {
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
        PORT: '9005',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '8',
        TICKETS_CACHE_TTL: '10',
        DASHBOARD_CACHE_TTL: '15',
        CACHE_MAX_BYTES: '4194304',
        DAILY_EXPORT_MAX_ROWS: '100000',
        TECH_PERFORMANCE_EXPORT_MAX_ROWS: '10000',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      listen_timeout: 15000,
      health_check_grace_period: 3000,
      error_file: '/var/log/dompis/web-error.log',
      out_file: '/var/log/dompis/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-ops-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '614M',
      node_args: '--max-old-space-size=768',
      env: {
        NODE_ENV: 'production',
        CRON_ENABLED: 'true',
        WORKER_STARTUP_DELAY_MS: '40000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '8',
        EXTERNAL_DB_CONNECTION_LIMIT: '6',
        EXTERNAL_DB_CONNECT_TIMEOUT_MS: '10000',
        DLQ_RETRY_INTERVAL_MINUTES: '5',
        HEALTH_CHECK_INTERVAL_MINUTES: '15',
        RECONCILIATION_ENABLED: 'true',
        RECONCILIATION_CRON: '0 6 * * *',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/ops-worker-error.log',
      out_file: '/var/log/dompis/ops-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-ingestion-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-ingestion.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '870M',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '0',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '6',
        PRISMA_SLOW_QUERY_MS: '2000',
        EXTERNAL_DB_CONNECTION_LIMIT: '6',
        EXTERNAL_DB_CONNECT_TIMEOUT_MS: '10000',
        INGESTION_ENABLED: 'true',
        INGESTION_INTERVAL_MINUTES: '1',
        INGESTION_TIMEOUT_MINUTES: '15',
        INGESTION_LOCK_TTL_SECONDS: '900',
        INGESTION_CHUNK_SIZE: '300',
        INGESTION_BATCH_SIZE: '500',
        INGESTION_WRITE_CHUNK_SIZE: '250',
        INGESTION_CONCURRENCY: '2',
        INGESTION_RETRY_MAX: '3',
        INGESTION_RETRY_BASE_MS: '250',
        INGESTION_CIRCUIT_RESET_MINUTES: '10',
        INGESTION_RUN_ON_START: 'true',
        INGESTION_TRIGGER_PROJECTION: 'true',
        INGESTION_CURSOR_STALE_HOURS: '24',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/ingestion-worker-error.log',
      out_file: '/var/log/dompis/ingestion-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-projection-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-projection.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '870M',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '10000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '6',
        PRISMA_SLOW_QUERY_MS: '2000',
        PROJECTION_ENABLED: 'true',
        PROJECTION_INTERVAL_MINUTES: '1',
        PROJECTION_TIMEOUT_MINUTES: '15',
        PROJECTION_LOCK_TTL_SECONDS: '900',
        PROJECTION_BATCH_SIZE: '250',
        PROJECTION_WRITE_CHUNK_SIZE: '250',
        PROJECTION_CONCURRENCY: '1',
        PROJECTION_RETRY_MAX: '3',
        PROJECTION_RETRY_BASE_DELAY_MS: '250',
        PROJECTION_TRANSACTION_TIMEOUT_MS: '60000',
        PROJECTION_CIRCUIT_RESET_MINUTES: '10',
        PROJECTION_FULL_SCAN_ENABLED: 'true',
        PROJECTION_FULL_SCAN_CRON: '*/30 * * * *',
        PROJECTION_RUN_ON_START: 'true',
        TICKETS_CACHE_TTL: '15',
        DASHBOARD_CACHE_TTL: '30',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/projection-worker-error.log',
      out_file: '/var/log/dompis/projection-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-active-refresh-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-active-refresh.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '435M',
      node_args: '--max-old-space-size=512',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '30000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '6',
        PRISMA_SLOW_QUERY_MS: '2000',
        ACTIVE_REFRESH_ENABLED: 'true',
        ACTIVE_REFRESH_INTERVAL_MINUTES: '5',
        ACTIVE_REFRESH_BATCH_SIZE: '50',
        ACTIVE_REFRESH_MIN_BATCH_SIZE: '40',
        ACTIVE_REFRESH_MAX_BATCH_SIZE: '150',
        ACTIVE_REFRESH_MAX_SCAN_PER_RUN: '500',
        ACTIVE_REFRESH_TIMEOUT_MINUTES: '5',
        ACTIVE_REFRESH_LOCK_TTL_SECONDS: '300',
        ACTIVE_REFRESH_FAST_RUN_THRESHOLD_MS: '10000',
        ACTIVE_REFRESH_SLOW_RUN_THRESHOLD_MS: '60000',
        ACTIVE_REFRESH_MAX_CONSECUTIVE_ERRORS: '5',
        ACTIVE_REFRESH_CIRCUIT_RESET_MINUTES: '10',
        ACTIVE_REFRESH_RUN_ON_START: 'true',
        SCHEDULE_OFFSET: '45',
        RUN_ON_START: 'true',
        TICKETS_CACHE_TTL: '15',
        DASHBOARD_CACHE_TTL: '30',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/active-refresh-worker-error.log',
      out_file: '/var/log/dompis/active-refresh-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
    {
      name: 'dompis-status-refresh-worker',
      script: 'node',
      args: '-r ./dist-workers/register-paths.cjs dist-workers/worker-status-refresh.js',
      cwd: '/www/wwwroot/dompis_v2',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '435M',
      node_args: '--max-old-space-size=512',
      env: {
        NODE_ENV: 'production',
        WORKER_STARTUP_DELAY_MS: '20000',
        NEXT_TELEMETRY_DISABLED: '1',
        REDIS_PORT: '6379',
        PRISMA_CONNECTION_LIMIT: '6',
        PRISMA_SLOW_QUERY_MS: '2000',
        STATUS_REFRESH_ENABLED: 'true',
        STATUS_REFRESH_INTERVAL_MINUTES: '1',
        STATUS_REFRESH_BATCH_SIZE: '100',
        STATUS_REFRESH_MIN_BATCH_SIZE: '50',
        STATUS_REFRESH_MAX_BATCH_SIZE: '200',
        STATUS_REFRESH_RECHECK_MINUTES: '2',
        STATUS_REFRESH_UPDATE_CHUNK_SIZE: '25',
        STATUS_REFRESH_SEED_BATCH_SIZE: '50',
        STATUS_REFRESH_SEED_TIMEOUT_MS: '15000',
        STATUS_REFRESH_TIMEOUT_MINUTES: '5',
        STATUS_REFRESH_LOCK_TTL_SECONDS: '300',
        STATUS_REFRESH_FAST_RUN_THRESHOLD_MS: '10000',
        STATUS_REFRESH_SLOW_RUN_THRESHOLD_MS: '60000',
        STATUS_REFRESH_MAX_CONSECUTIVE_ERRORS: '5',
        STATUS_REFRESH_CIRCUIT_RESET_MINUTES: '10',
        STATUS_REFRESH_RUN_ON_START: 'true',
        STATUS_REFRESH_TRIGGER_PROJECTION: 'true',
      },
      autorestart: true,
      watch: false,
      kill_timeout: 30000,
      error_file: '/var/log/dompis/status-refresh-worker-error.log',
      out_file: '/var/log/dompis/status-refresh-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      max_size: '10M',
      rotate: 7,
    },
  ],
};
