import prisma from '../app/libs/prisma';

async function main() {
  console.log('🌱 Seeding source_vlookup...\n');

  await prisma.$executeRaw`
    INSERT INTO source_vlookup (value_id, description, jenis_tiket, customer_type_key, jenis_tiket_2_val, realm_b2b, flag_1, flag_2) VALUES
      (1, 'Digital CC', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (2, 'Agent 147', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (3, 'MyTelkom', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (4, 'Walk-In / Plasa Telkom', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (5, 'Email', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (6, 'MyIndihome Customer', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (8, 'Proactive WiFi AP', 'Wifi AP', NULL, NULL, NULL, NULL, NULL),
      (9, 'Proactive iBooster', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (10, 'Agent C4 DES/DGS', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (11, 'Agent TAM DBS', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (12, 'Agent OCC DWS', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (14, 'Agent MSOC DSS', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (15, 'Proactive SmartSolver', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (16, 'MySolution Customer', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (17, 'AM Tool', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (18, 'IDEAS', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (19, 'Agent Social Media', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (20, 'WebCare', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (21, 'Remedy Telkomsel', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (22, 'MySmart Business Mobile Web', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (23, 'TAM Consumer', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (24, 'TELIN', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (25, 'DDS', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (26, 'GRAPARI Telkom Group', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (27, 'MyCarrier', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (28, 'Proactive_Maintenance', 'UNSPEC', NULL, NULL, NULL, NULL, NULL),
      (29, 'COM', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (30, 'TELKOMCARE', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (31, 'MyWicoWista', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (32, 'Salam Perdana', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (33, 'Remedy Sigma', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (34, 'Snow Telstra', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (35, 'TDS (Telkom Digital Solution)', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (36, 'Proactive Maintenance ODP', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (37, 'Proactive_SPBU_Pertamina', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (38, 'Proactive_Maintenance SERVO', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (39, 'VVIP Proactive Ticket', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (40, 'MyIndihome X', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (41, 'MyDigiBiz', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (42, 'SDMS Proactive SPBU', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (43, 'Diagram Sisir DSO', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (44, 'InfraCare', 'InfraCare', NULL, NULL, NULL, NULL, NULL),
      (45, 'DALAPA', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (46, 'REVAS SSOF', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (47, 'SMART SURVEILANCE', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (50, 'SQM Predictive Ticket', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (52, 'Order Bulk FF', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (53, 'Agent Salam Simpatik', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (54, 'MKIOSK', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (55, 'Mantools Telkomsat', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (56, 'CTS Telkomsel', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (57, 'Digital', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (58, 'UT Online', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (59, 'LPISDH', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (60, 'YAF', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (61, 'WA_INTERAKTIF', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (62, 'CRA (Change Release Activity)', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (65, 'LPIH', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (66, 'WA IndiHome Care', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (67, 'FAB Digital', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (68, 'EOS SDA', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (69, 'MyIndibiz', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (70, 'SQM Logic', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (71, 'Agent Voice TENESA', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (72, 'Agent SocMed TENESA', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (73, 'Agent Chat TENESA', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (74, 'Agent Email TENESA', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (83, 'PRA-SQM', 'SQM', NULL, NULL, NULL, NULL, NULL),
      (86, 'VERONIKA', 'Reguler', NULL, NULL, NULL, NULL, NULL),
      (100, 'PREVENTIF CCAN', 'CCAN-PREV', NULL, NULL, NULL, NULL, NULL),
      (117, 'Walk-in INDEX', 'Regular', NULL, NULL, NULL, NULL, NULL),
      (118, 'ICC - PLASA INDIBIZ', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (119, 'ICC - SOCMED', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (124, 'ICC - VAM', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (161, 'BUSSINESE SERVICE WITEL SURAMADU', 'CCAN', NULL, NULL, NULL, NULL, NULL),
      (162, NULL, NULL, 'REGULER', 'REG', NULL, NULL, NULL),
      (163, NULL, NULL, 'HVC_SILVER', 'REG', NULL, NULL, NULL),
      (164, NULL, NULL, 'HVC_GOLD', 'REG', NULL, NULL, NULL),
      (165, NULL, NULL, 'HVC_PLATINUM', 'HVC', NULL, NULL, NULL),
      (166, NULL, NULL, 'HVC_DIAMOND', 'HVC', NULL, NULL, NULL),
      (167, NULL, NULL, 'NON-INDIHOME', 'CCAN', NULL, NULL, NULL),
      (168, NULL, NULL, 'GOLD', 'REG', NULL, NULL, NULL),
      (169, NULL, NULL, 'PLATINUM', 'HVC', NULL, NULL, NULL),
      (170, NULL, NULL, 'DIAMOND', 'HVC', NULL, NULL, NULL),
      (171, NULL, NULL, 'VVIP', 'HVC', NULL, NULL, NULL),
      (172, NULL, NULL, 'INPUTAN-CCAN', 'CCAN-PREV', NULL, NULL, NULL),
      (173, NULL, NULL, 'DATIN - K2', 'CCAN', NULL, NULL, NULL),
      (174, NULL, NULL, 'INDIBIZ', 'CCAN', NULL, NULL, NULL),
      (175, NULL, NULL, 'SQM - CCAN', 'CCAN', NULL, NULL, NULL),
      (176, NULL, NULL, 'Regular', 'CCAN', NULL, NULL, NULL),
      (177, NULL, NULL, 'PERMINTAAN', 'PERMINTAAN', NULL, NULL, NULL),
      (178, NULL, NULL, 'InfraCare', 'REG', NULL, NULL, NULL),
      (179, NULL, NULL, 'Ruby', 'CCAN', NULL, NULL, NULL),
      (180, NULL, NULL, NULL, NULL, 'DATIN', 'DATIN', 'DATIN'),
      (181, NULL, NULL, NULL, NULL, 'VPNIP', 'VPNIP', 'VPNIP'),
      (182, NULL, NULL, NULL, NULL, 'INF_IPPBX', 'SIP_TRUNK', 'SIP_TRUNK'),
      (183, NULL, NULL, NULL, NULL, 'MM_ASTINET', 'ASTINET', 'ASTINET'),
      (184, NULL, NULL, NULL, NULL, 'MM_INTER_METRO', 'METRO_E', 'METRO_E'),
      (185, NULL, NULL, NULL, NULL, 'MM_IP_TRANSIT', 'IP_TRANSIT', 'IP_TRANSIT'),
      (186, NULL, NULL, NULL, NULL, 'MM_IPVPN', 'VPNIP', 'VPNIP'),
      (187, NULL, NULL, NULL, NULL, 'METRO-E', 'METRO_E', 'METRO_E'),
      (188, NULL, NULL, NULL, NULL, 'MM_METRO_ETHERN', 'METRO_E', 'METRO_E'),
      (189, NULL, NULL, NULL, NULL, 'MM_METRO_ETHERNET', 'METRO_E', 'METRO_E'),
      (190, NULL, NULL, NULL, NULL, 'ASTINET', 'ASTINET', 'ASTINET'),
      (191, NULL, NULL, NULL, NULL, 'MM_NEWINTER_METRO', 'METRO_E', 'METRO_E'),
      (192, NULL, NULL, NULL, NULL, 'MM_TRANS_ACCESS', 'VPNIP', 'VPNIP'),
      (193, NULL, NULL, NULL, NULL, 'MM_UHOS', 'DATIN', 'DATIN'),
      (194, NULL, NULL, NULL, NULL, 'SDWAN', 'DATIN', 'DATIN'),
      (195, NULL, NULL, NULL, NULL, 'SIP_TRUNK', 'SIP_TRUNK', 'SIP_TRUNK'),
      (196, NULL, NULL, NULL, NULL, 'MM_WIFI_BISNIS', 'WIFI-ID', 'NON-DATIN'),
      (197, NULL, NULL, NULL, NULL, 'MM_WIFI_ID', 'WIFI-ID', 'NON-DATIN'),
      (198, NULL, NULL, NULL, NULL, 'MM_WIFI_VAS', 'WIFI-ID', 'NON-DATIN'),
      (199, NULL, NULL, NULL, NULL, 'WICO', 'WIFI-ID', 'NON-DATIN'),
      (200, NULL, NULL, NULL, NULL, 'WIFI', 'WIFI-ID', 'NON-DATIN'),
      (201, NULL, NULL, NULL, NULL, 'WIFI MESH', 'WIFI-ID', 'NON-DATIN'),
      (202, NULL, NULL, NULL, NULL, 'WIFI_AP', 'WIFI-ID', 'NON-DATIN'),
      (203, NULL, NULL, NULL, NULL, 'WIFI_HOMESPOT', 'WIFI-ID', 'NON-DATIN'),
      (204, NULL, NULL, NULL, NULL, 'WISTA', 'WIFI-ID', 'NON-DATIN'),
      (205, NULL, NULL, NULL, NULL, 'WMSLITE', 'WIFI-ID', 'NON-DATIN'),
      (206, NULL, NULL, NULL, NULL, 'NON-NUMBERING', 'RESELLER', 'NON-DATIN'),
      (207, NULL, NULL, NULL, NULL, 'INTERNET', 'RESELLER', 'NON-DATIN'),
      (208, NULL, NULL, NULL, NULL, 'IPTV', 'RESELLER', 'NON-DATIN'),
      (209, NULL, NULL, NULL, NULL, 'VOICE', 'RESELLER', 'NON-DATIN'),
      (210, NULL, NULL, NULL, NULL, 'telkom.b2b', 'INDIBIZ', 'NON-DATIN'),
      (211, NULL, NULL, NULL, NULL, 'Diamond', 'HVC-EBIS', 'NON-DATIN'),
      (212, NULL, NULL, NULL, NULL, 'Ruby', 'HVC-EBIS', 'NON-DATIN'),
      (213, NULL, NULL, NULL, NULL, 'Emerald', 'HVC-EBIS', 'NON-DATIN'),
      (214, NULL, NULL, NULL, NULL, 'Saphire', 'HVC-EBIS', 'NON-DATIN'),
      (215, NULL, NULL, NULL, NULL, 'VVIP Customer', 'HVC-EBIS', 'NON-DATIN'),
      (216, NULL, NULL, NULL, NULL, 'Platinum', 'HSI-EBIS', 'NON-DATIN'),
      (217, NULL, NULL, NULL, NULL, 'Gold', 'HSI-EBIS', 'NON-DATIN'),
      (218, NULL, NULL, NULL, NULL, 'SITE', 'TSEL', 'TSEL'),
      (219, NULL, NULL, NULL, NULL, 'Wifi Managed Service', 'WIFI-ID', 'NON-DATIN'),
      (220, NULL, NULL, 'DWDM', 'DWDM', NULL, NULL, NULL)
    ON DUPLICATE KEY UPDATE
      description = VALUES(description),
      jenis_tiket = VALUES(jenis_tiket),
      customer_type_key = VALUES(customer_type_key),
      jenis_tiket_2_val = VALUES(jenis_tiket_2_val),
      realm_b2b = VALUES(realm_b2b),
      flag_1 = VALUES(flag_1),
      flag_2 = VALUES(flag_2)
  `;

  const count = await prisma.sourceVlookup.count();
  console.log(`✅ Seeded ${count} records into source_vlookup`);
  console.log('🎉 Done!\n');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
