export interface ExternalRow {
  id?: number;
  col_0?: string | null;
  c_parent_id?: string | null;
  incident?: string | null;
  ttr_customer?: string | null;
  summary?: string | null;
  reported_date?: string | null;
  owner_group?: string | null;
  owner?: string | null;
  customer_segment?: string | null;
  service_type?: string | null;
  witel?: string | null;
  workzone?: string | null;
  status?: string | null;
  status_date?: string | null;
  ticket_id_gamas?: string | null;
  reported_by?: string | null;
  contact_phone?: string | null;
  contact_name?: string | null;
  contact_email?: string | null;
  booking_date?: string | null;
  description_assignment?: string | null;
  reported_priority?: string | null;
  source_ticket?: string | null;
  subsidiary?: string | null;
  external_ticket_id?: string | null;
  channel?: string | null;
  customer_type?: string | null;
  closed_by?: string | null;
  closed_reopen_by?: string | null;
  customer_id?: string | null;
  customer_name?: string | null;
  service_id?: string | null;
  service_no?: string | null;
  slg?: string | null;
  technology?: string | null;
  lapul?: string | null;
  gaul?: string | null;
  onu_rx?: string | null;
  pending_reason?: string | null;
  datemodified?: string | null;
  incident_domain?: string | null;
  region?: string | null;
  symptom?: string | null;
  hierarchy_path?: string | null;
  solution?: string | null;
  description_actual_solution?: string | null;
  kode_produk?: string | null;
  perangkat?: string | null;
  technician?: string | null;
  device_name?: string | null;
  worklog_summary?: string | null;
  last_update_worklog?: string | null;
  classification_flag?: string | null;
  realm?: string | null;
  related_to_gamas?: string | null;
  tsc_result?: string | null;
  scc_result?: string | null;
  ttr_agent?: string | null;
  ttr_mitra?: string | null;
  ttr_nasional?: string | null;
  ttr_pending?: string | null;
  ttr_region?: string | null;
  ttr_witel?: string | null;
  ttr_end_to_end?: string | null;
  note?: string | null;
  guarantee_status?: string | null;
  resolve_date?: string | null;
  sn_ont?: string | null;
  tipe_ont?: string | null;
  manufacture_ont?: string | null;
  impacted_site?: string | null;
  cause_problem?: string | null;
  resolution?: string | null;
  notes_eskalasi?: string | null;
  rk_information?: string | null;
  external_ticket_tier3?: string | null;
  customer_category?: string | null;
  classification_path?: string | null;
  teritory_near_end?: string | null;
  teritory_far_end?: string | null;
  urgency?: string | null;
  urgency_description?: string | null;
  c_street_address?: string | null;
  col_83?: string | null;
  status_validasi?: 'OPEN' | 'CLOSE' | 'PENDING' | 'UNKNOWN' | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface NormalizedExternalRow {
  incident: string | null;
  ttr_customer: string | null;
  summary: string | null;
  reported_date: string | null;
  owner_group: string | null;
  owner: string | null;
  customer_segment: string | null;
  service_type: string | null;
  witel: string | null;
  workzone: string | null;
  status: string | null;
  status_date: string | null;
  ticket_id_gamas: string | null;
  reported_by: string | null;
  contact_phone: string | null;
  contact_name: string | null;
  contact_email: string | null;
  booking_date: string | null;
  description_assignment: string | null;
  reported_priority: string | null;
  source_ticket: string | null;
  subsidiary: string | null;
  external_ticket_id: string | null;
  channel: string | null;
  customer_type: string | null;
  closed_by: string | null;
  closed_reopen_by: string | null;
  customer_id: string | null;
  customer_name: string | null;
  service_id: string | null;
  service_no: string | null;
  slg: string | null;
  technology: string | null;
  lapul: string | null;
  gaul: string | null;
  onu_rx: string | null;
  pending_reason: string | null;
  date_modified: string | null;
  incident_domain: string | null;
  region: string | null;
  symptom: string | null;
  hierarchy_path: string | null;
  solution: string | null;
  description_actual_solution: string | null;
  kode_produk: string | null;
  perangkat: string | null;
  technician: string | null;
  device_name: string | null;
  worklog_summary: string | null;
  last_update_worklog: string | null;
  classification_flag: string | null;
  realm: string | null;
  related_to_gamas: string | null;
  tsc_result: string | null;
  scc_result: string | null;
  ttr_agent: string | null;
  ttr_mitra: string | null;
  ttr_nasional: string | null;
  ttr_pending: string | null;
  ttr_region: string | null;
  ttr_witel: string | null;
  ttr_end_to_end: string | null;
  note: string | null;
  guarantee_status: string | null;
  resolve_date: string | null;
  sn_ont: string | null;
  tipe_ont: string | null;
  manufacture_ont: string | null;
  impacted_site: string | null;
  cause: string | null;
  resolution: string | null;
  notes_eskalasi: string | null;
  rk_information: string | null;
  external_ticket_tier_3: string | null;
  customer_category: string | null;
  classification_path: string | null;
  teritory_near_end: string | null;
  teritory_far_end: string | null;
  urgency: string | null;
  urgency_description: string | null;
  street_address: string | null;

  _sourceTable: string;
  _rawPayload: Record<string, unknown>;
}

export interface IdentityResolution {
  primaryIdentity: string;
  fallback1Identity: string | null;
  fallback2Identity: string | null;
}

export type SyncResult = {
  syncBatchId?: string;
  inserted: number;
  updated: number;
  skipped: number;
  failed: number;
  errors: Array<{
    table: string;
    incident: string;
    error: string;
  }>;
};

export type IngestionMetrics = {
  startTime: Date;
  endTime?: Date;
  tableName: string;
  totalRows: number;
  processedRows: number;
  inserted: number;
  updated: number;
  skipped: number;
  failed: number;
  status: 'running' | 'completed' | 'failed';
  error?: string;
};
